# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate

# Параметры стандартного плагина пагинации
paginate: 10
paginate_path: "/page:num/"

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: 'en_GB'
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

############################################################
# Общие настройки сайта
footer_text: "© 2025 Ivan Smirnov"
admin_name: "Ivan Smirnov"
google_analytics: "UA-9999999-99"
enable_contact: false
enable_nav: true

# =========================
# Английские тексты
# =========================
title_en: "The Grotto"
description_en: "Hello! This is my portfolio. I'm primarily a backend developer, but sometimes I enjoy working on full-stack as well."

section_title_en: "Latest Works"
section_subtitle_en: "My experience is quite broad, but these projects were especially interesting"

nav_item_en:
#  - { url: '/', text: 'Home' }
  # - { url: '/about', text: 'About' }

# =========================
# Русские тексты
# =========================
title_ru: "Грот"
description_ru: "Привет! Это моё портфолио. Я в основном занимаюсь бэкендом, но иногда люблю поработать и во фулстэк."

section_title_ru: "Последние работы"
section_subtitle_ru: "Мой опыт распространяется довольно широко, но эти проекты были особенно интересными"

nav_item_ru:
#  - { url: '/ru/', text: 'Главная' }
  # - { url: '/ru/about', text: 'О сайте' }

############################################################
# GitHub Pages
baseurl: ""
url: "https://meowypouncer.github.io"

github_username: "meowypouncer"
medium_username: "t.me/surelyou"
bluesky_username: "meowy-pouncer.bsky.social"  # Пример
